"""fix models

Revision ID: ad03aeb0d40a
Revises: 13c3745878ba
Create Date: 2025-11-22 15:20:51.629833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ad03aeb0d40a'
down_revision: Union[str, Sequence[str], None] = '13c3745878ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('status', sa.Enum('ACTIVE', 'CLOSED', name='session_status'), nullable=False))
    op.drop_column('sessions', 'session_status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('session_status', postgresql.ENUM('ACTIVE', 'CLOSED', name='session_status'), autoincrement=False, nullable=False))
    op.drop_column('sessions', 'status')
    # ### end Alembic commands ###
